### ISSUE TITLE
How does GAP adjusts the SH degree?

### ISSUE THREAD

**Issue by LiuJingCheng6** [CUHK-AIM-Group/LGS#1]
Thanks for your excellent work. But I have some questions. It can be seen from the paper that "GAP adjusts the SH degree from high to low, which effectively reduces the redundancy of each Gaussian’s attributes.",  However, i can't find which code relate to this, can you help me?

**Comment by LiuJingCheng6** [comment]
Furthermore, 

- Could you elaborate on how the adaptive process is implemented in Feature Field Condensation? Do we have the flexibility to define multiple specific resolutions, or is there a predefined set?
- What is the methodology for obtaining the teacher model?

**Comment by LiuHengyu321** [comment]
Hi @LiuJingCheng6,

Thank you for your interest in our work! Here are some details regarding the code and its functionalities:

(1) The code related to GAP begins at line 123 in `train.py`. You can use the `--prune_sh` flag to conduct this operation.
(2) FFC can be operated using the `--prune_deform` flag in `train.py`. As mentioned in the paper, FFC is implemented by a 3D adaptive pooling, and the related code can be found in `gaussian_model.py`. The resolutions can be defined in the configuration files for each dataset under arguments.
(3) The teacher model can be obtained by training [EndoGaussian](https://github.com/yifliu3/EndoGaussian). Thank you for reminding me about this, I will update the repository accordingly.

**Comment by LiuJingCheng6** [comment]
Understood, thank you for your patient explanation!
