### ISSUE TITLE
The link to 'submodules/compress-diff-gaussian-rasterization' is broken

### ISSUE THREAD

**Issue by fusheng-ji** [CUHK-AIM-Group/LGS#2]
Hi, thanks for such a fantastic project!
As mentioned in the title, the link 'https://github.com/CUHK-AIM-Group/LGS/blob/main/submodules/compress-diff-gaussian-rasterization' is unreachable. Could you fix this problem?

**Comment by LiuHengyu321** [comment]
Hi @fusheng-ji! Thank you for your interest in our work!

The valid link is [here](https://github.com/Kevin-2017/compress-diff-gaussian-rasterization/tree/240618bbc5fb21c270a0c5babb292615011a2f15). Thank you for your reminder and I will update this to repository..

**Comment by fusheng-ji** [comment]
Thanks for your reply. :) I have successfully installed it.

**Comment by fusheng-ji** [comment]
Thanks for your reply. :) I have successfully installed it.
