### ISSUE TITLE
Questions about the training parameters

### ISSUE THREAD

**Issue by fusheng-ji** [CUHK-AIM-Group/LGS#3]
Hi,
I am using the script you provided in README to train LGS in a distillation scheme.

But I am so confused about the parameters used in `train.py`, for example:
`parser.add_argument("--start_checkpoint", type=str, default = "/path/to/teacher/model/")`
 `parser.add_argument("--deformatioin_model_path", type=str, default="/path/to/teacher/model/")`
 `parser.add_argument("--teacher_model", type=str, default="/path/to/teacher/model/")`
All of them are described as `the path to teacher model`, but what are their specific meanings?

Moreover, as I already successfully trained EndoGaussian and got the checkpoint, I didn't find the `*.ckpt` file needed in train script:`check_point="/path/to/teacher/model/.ckpt".` I got only the `deformation*.pth` in the output folder. Did I miss some important steps? I would appreciate it if you could help me to solve such problems.

Could you please specify these usages in README? That will be very helpful in reproducing your awesome work. Thanks a lot. :)

Best

**Comment by LiuHengyu321** [comment]
Hi @fusheng-ji,

Thank you very much for your interest in our work!

Here are the details of the training script:

(1) `--start_checkpoint` and `--teacher_model` are both paths to load the teacher model. They load different parts of the model. The code is somewhat repetitive, and I will clean it up.
(2) `deformation_model_path` should be set to the exact iteration file in the training output. Meanwhile, `--start_checkpoint` and `--teacher_model` should be set to the exact .pth path, like:

```
check_point="/path/to/output/chkpnt3000.pth"
deformation_path="/path/to/output/point_cloud/iteration_3000"

python train.py \
    --start_checkpoint $check_point \
    --deformatioin_model_path $deformation_path \
    --teacher_model $check_point \
```

  There is no `*.ckpt` files, but `.pth` for the saved checkpoint files.

**Comment by fusheng-ji** [comment]
Thanks for your patient reply! I have modified the script and tried to run it, but I got the errors.
I used the setting below:
> dataset="endonerf"
> test_name="cutting"
> config_name="arguments/endonerf/cutting_distill.py"
> 
> check_point="./endogauss_output/endonerf/cutting/chkpnt3000.pth"
> deformation_path="./endogauss_output/endonerf/cutting/point_cloud/iteration_3000/"
> 
> python train.py \
>     -s ./datasets/endonerf/cutting_tissues_twice/ \
>     -m ./lgs_output/ \
>     --expname $dataset/$test_name \
>     --start_checkpoint $check_point \
>     --deformatioin_model_path $deformation_path \
>     --teacher_model $check_point \
>     --enable_covariance \
>     --new_max_sh 2 \
>     --iteration 4000 \
>     --configs $config_name \
>     --prune_percent 0.3 \
>     --prune_decay 0.6 \
>     --prune_iterations 2000 \
>     --prune \
>     --prune_sh \
>     --v_pow 0.1 \
>     --port 6036 > ./log/cutting_log

Then the training process raises the error like:

> Traceback (most recent call last):
>   File "/storage/user/jiw/run/LGS/train.py", line 311, in <module>
>     distill_training(
>   File "/storage/user/jiw/run/LGS/train.py", line 129, in distill_training
>     gaussian_list, imp_list, opacity_list, delta_scale_list = prune_list(student_gaussians, student_scene, pipe, background, distill_feature=distill_feature)
>   File "/storage/user/jiw/run/LGS/prune.py", line 64, in prune_list
>     render_pkg = count_deformation_render(viewpoint_cam, gaussians, pipe, background, distill_feature=distill_feature)
>   File "/storage/user/jiw/run/LGS/gaussian_renderer/__init__.py", line 331, in count_deformation_render
>     means3D_deform, scales_deform, rotations_deform, opacity_deform = pc._deformation(means3D[deformation_point], scales[deformation_point],
> IndexError: The shape of the mask [36248] at index 0 does not match the shape of the indexed tensor [36274, 3] at index 0


Furthermore, I am confused with the parameter `--iteration 4000` in the script; the corresponding relationship between it and `--test_iterations` / `--save_iterations` / `--checkpoint_iterations` is unclear.
Sorry for lots of questions :P, hope you have a good day.

**Comment by LiuHengyu321** [comment]
I have checked the training script in the repository and realized I forgot to add some variables. I have fixed this issue and updated the repository.
