### ISSUE TITLE
check_point and deformation_path

### ISSUE THREAD

**Issue by Beilinlin** [CUHK-AIM-Group/LGS#4]
The training sentence you provided, 
check_point="/path/to/teacher/model/chkpntN.pth" 
and deformation_path="/path/to/teacher/model/point_cloud/iteration_N",
how can these paths be obtained? Thank you very much!

**Comment by LiuHengyu321** [comment]
Hi @Beilinlin!

These paths are the output and the pretrained weights of teacher model, which can be obtained by training [Endogaussian](https://github.com/CUHK-AIM-Group/EndoGaussian).
