### ISSUE TITLE
 size mismatch problem

### ISSUE THREAD

**Issue by Caizeyu116** [CUHK-AIM-Group/LGS#6]
I encountered a problem while attempting to use pre-trained teacher models from EndoGaussian for training in LGS. During the loading of the model weights, I faced size mismatch errors between the parameters of the pre-trained model and those in the current model. Here is the error traceback I received:

Traceback (most recent call last):
  File "train.py", line 315, in <module>
    args, 
  File "train.py", line 117, in distill_training
    teacher_gaussians.load_model(args.deformatioin_model_path)
  File "/root/autodl-tmp/project/LGS/scene/gaussian_model.py", line 273, in load_model
    self._deformation.load_state_dict(weight_dict)
  File "/root/miniconda3/envs/lgs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for deform_network:
        size mismatch for deformation_net.grid.grids.0.0: copying a param with shape torch.Size([1, 32, 64, 64]) from checkpoint, the shape in current model is torch.Size([1, 64, 64, 64]).
        (Additional error messages detailing size mismatches for various parameters follow...)

Each line of the error details a size mismatch for various layers, indicating that the parameters from the checkpoint have a different shape compared to those expected by the current model architecture. How can I resolve this issue to successfully load and utilize the pre-trained models?

**Comment by LiuHengyu321** [comment]
Hi @caituanzi31!

Thank you for your interest in our work! You are correct about the size mismatch problem; I made a mistake in the repository. The resolution of the teacher model (Endogaussian) should be set to 64, the same as LGS's configuration. In other words, we don't use the original setting of EndoGaussian for the "resolution" parameter. It should be set as follows:

kplanes_config = {
    'grid_dimensions': 2,
    'input_coordinate_dim': 4,
    'output_coordinate_dim': 64,
    'resolution': [64, 64, 64, 100]
}

Thank you for pointing this out. I will update this setting in the repository!
